# Generated by Django 4.0.4 on 2022-07-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cerro',
            options={'verbose_name': 'Cerro', 'verbose_name_plural': 'Cerros del Ecuador'},
        ),
        migrations.AlterModelOptions(
            name='latitud',
            options={'verbose_name': 'Latitud', 'verbose_name_plural': 'Latitudes'},
        ),
        migrations.AlterModelOptions(
            name='longitud',
            options={'verbose_name': 'Longitud', 'verbose_name_plural': 'Longitudes'},
        ),
        migrations.AlterField(
            model_name='latitud',
            name='seconds',
            field=models.FloatField(verbose_name='Seconds'),
        ),
        migrations.AlterField(
            model_name='longitud',
            name='seconds',
            field=models.FloatField(verbose_name='Seconds'),
        ),
    ]
